services:
  mysql_db:
    image: mysql:8.0
    container_name: leave_management_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: leave_management
      MYSQL_USER: adonis_user
      MYSQL_PASSWORD: adonis_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: