export const LogEvents = {
  // OAUTH & AUTH
  AUTH_NEW_USER: 'NEW USER REGISTERED',
  AUTH_LOGIN: 'USER LOGIN',
  AUTH_OAUTH_LINKED: 'OAUTH_ACCOUNT_LINKED_TO_EXISTING_USER',
  
  // LEAVE APPLICATIONS
  LEAVE_STATUS_UPDATED: 'LEAVE_APPLICATION_STATUS_UPDATED',
  LEAVE_APPLIED: 'LEAVE_APPLICATION_CREATED',
  LEAVE_APPROVED: 'LEAVE_APPLICATION_APPROVED',
  LEAVE_REJECTED: 'LEAVE_APPLICATION_REJECTED',
  LEAVE_CREATED: 'LEAVE_APPLICATION_CREATED',
  LEAVE_BALANCE_REFUNDED: 'LEAVE_BALANCE_REFUNDED',
  LEAVE_GET_ALL_SUCCESS: 'LEAVE_GET_ALL_SUCCESS',

  SYSTEM_CRASH: 'SYSTEM CRASH',
  SYSTEM_ERROR: 'SYSTEM ERROR',
  UNHANDLED_ERROR: 'UNHANDLED ERROR',
  FRAMEWORK_ERROR: 'FRAMEWORK ERROR',
  SECURITY_WARN: 'SECURITY WARNING',
  CLIENT_ERROR: 'CLIENT ERROR',
}